function [ys_, params, info] = ramsey_levels_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    val=params(3)*params(1)*(1+params(5))^(-params(2))/(1-params(1)*(1+params(5))^(-params(2))*(1-params(4)));
    ys_(1)=(1+params(5))*(1+params(6))*val^(1/(1-params(3)));
    ys_(3)=1.0;
    ys_(2)=(1-params(4))*ys_(1)/((1+params(5))*(1+params(6)))+(ys_(1)/((1+params(5))*(1+params(6))))^params(3)-ys_(1);
    % Auxiliary equations
    check_=0;
end
